### ISSUE TITLE
Can't run the code, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by harewei** [carpedm20/ENAS-pytorch#17]
I suppose I'm the only one with this problem, seeing everyone else can actually run the program.

I tried both
```
python3 main.py --network_type rnn --dataset ptb --controller_optim adam --controller_lr 0.00035 \
               --shared_optim sgd --shared_lr 20.0 --entropy_coeff 0.0001

python3 main.py --network_type rnn --dataset wikitext
```
but an error comes out with 
```
File "main.py", line 28
    raise NotImplementedError(f"{args.dataset} is not supported")
                                                               ^
SyntaxError: invalid syntax
```

Does anyone have any idea why?  I'm using Ubuntu on Docker, with PyTorch installed (as well as those listed in requirement.txt, except pygraphviz (due to installation error, but this shouldn't raise any errors until it's actually called in utils.py, which I commented out anyway).

**Comment by beduffy** [comment]
`f"{args.dataset} is not supported"`

This is Python 3.6+ syntax. Trying removing the f or upgrading your python

**Comment by beduffy** [comment]
PyTorch 0.4.0 was released the other day with the addition of 0 dimensional tensors. In general, this will probably break all PyTorch tutorials and code.

I assume because of that error you have 0.4.0 but I could be wrong.

**Comment by harewei** [comment]
@beduffy That is indeed the issue. The program now runs fine when I use PyTorch 0.3.1 instead of 0.4.0.  Thank you.
